### PR TITLE
renamed htpasswd file and its references from `configmap` to `secret`

### PR DESCRIPTION
**Pull request by aiciobanu**
Contains the fix for issue #13 

Updated files:
 - Renamed `templates/configmap-htpasswd-file.yaml` to `templates/secret-htpasswd-file.yaml`
 - Updated the htpasswd file name reference inside `templates/deployment.yaml`

### CODE REVIEW

**Comment by pierluigilenoci** [comment]
@aiciobanu could you please fix the conflict?

**Comment by aiciobanu** [comment]
@pierluigilenoci Done.

**Review by desaintmartin — DISMISSED** [review]

**Comment by desaintmartin** [comment]
Unfortunately another merge has been done just now, could you rebase again?

**Comment by desaintmartin** [comment]
Thanks !

**Pull request merged**
