### PR TITLE
Way to disable appProtocol

### PR DESCRIPTION
**Pull request by none0nfg**
[K8s older than 1.20](https://kubernetes.io/docs/concepts/services-networking/service/#application-protocol), can't understand appProtocol in service description, so let's add way to disable appProtocol.

### CODE REVIEW

**Comment by none0nfg** [comment]
Just override appProtocol value to "", to disable it

**Comment by none0nfg** [comment]
@pierluigilenoci
I've tried to set `appProtocol: ""` in values.yaml, but k8s service gets the same `appProtocol: ""`, and so it's raising a error. 
The way with if, does'nt add appProtocol directive to service notation at all.

**Comment by pierluigilenoci** [comment]
Can you check the manifests generated by the Chart?
What you ask is already a feature of the chart.

**Comment by pierluigilenoci** [comment]
It was closed due to lack of feedback from the reporter.

**Pull request closed without merging**
