### PR TITLE
Support `--google-group` option

### PR DESCRIPTION
**Pull request by roeizavida**
This option is required when `--google-admin-email` and `--google-service-account-json` options are used, the service is crushing without it.
This PR adds support for this option in the Helm chart by using the `config.google.groups` parameter.

### CODE REVIEW

**Comment by pierluigilenoci** [comment]
@roeizavida a chart version bump is needed.

**Comment by roeizavida** [comment]
@pierluigilenoci Done, thanks!

**Comment by pierluigilenoci** [comment]
@desaintmartin could you please take a look?

**Review by desaintmartin — APPROVED** [review]

**Comment by desaintmartin** [comment]
Thanks! Could you rebase?

**Comment by roeizavida** [comment]
@desaintmartin Done.

**Review by desaintmartin — APPROVED** [review]

**Pull request merged**
