### PR TITLE
fix: helm warnings

### PR DESCRIPTION
**Pull request by gowrisankar22**
This PR fix the coalesce.go:199: warning: destination for annotations is a table. Ignoring non-table value [] warning
More details:
https://github.com/helm/helm/issues/4514

### CODE REVIEW

**Comment by desaintmartin** [comment]
Thanks! Most of them are string so it makes no sense to default them as dict...

**Comment by pierluigilenoci** [comment]
@gowrisankar22 could you please fix the PR?

**Comment by desaintmartin** [comment]
Unfortunately, tests are failing, you've probably gone too far in switching types! ;)

**Comment by pierluigilenoci** [comment]
@gowrisankar22 could you please fix the PR?

**Comment by gowrisankar22** [comment]
Sorry for the delay. I will close the PR. I dont have a time to take look at this.

**Pull request closed without merging**
