### PR TITLE
use password secret from redis subchart

### PR DESCRIPTION
**Pull request by bluebrown**
Signed-off-by: Nico Braun <rainbowstack@gmail.com>

Fixes : #84

### CODE REVIEW

**Comment by bluebrown** [comment]
I am not sure why the tests here fail. I have tested this locally. The chart works as is. It seems the test is looking for the secret, which is no longer created.

```bash
Warning  Failed     7m48s (x12 over 10m)  kubelet            Error: secret "oauth2-proxy-06u7ma6raq-redis-access" not found
```

I have added this to the secret, which can lead to a situation where it's not created. But in this case it should actually not get created, as far as I can tell. Maybe we need to adjust the tests for this.

```yaml
{{- with .Values.sessionStorage }}
{{- if and (eq .type "redis") (not .redis.existingSecret) (or .redis.password .redis.sentinel.password) }}
# create secret
```

**Comment by bluebrown** [comment]
I did not fully understand how the tests are created and run. I could add some additional test cases. Furthermore, I don't think this PR is actually covered, since it's setting the PW explicitly.

**Comment by pierluigilenoci** [comment]
@bluebrown this PR needs a rebase.

**Comment by bluebrown** [comment]
idk, I suck at git. Now its broken again.

**Comment by bluebrown** [comment]
It would be too bad if you did a squash commit when merging. Like this I try to rebase it in a single commit on my end but the confilcts keep staying.

**Comment by bluebrown** [comment]
Now its 2 commits. I didnt know how to do it better. Sorry.

**Comment by bluebrown** [comment]
I will do it again from master. I don't know, this rebase stuff is weird. Furthermore, I prefer a regular merge.

**Pull request closed without merging**
