### PR TITLE
Update oauth2-proxy to 7.1.3 & set default redis url if no one is defined in standalone mode

### PR DESCRIPTION
**Pull request by desaintmartin**
Replaces https://github.com/oauth2-proxy/manifests/pull/18

### CODE REVIEW

**Review by pierluigilenoci — APPROVED** [review]

**Comment by desaintmartin** [comment]
Well, I am not sure how the redis test could even work before. Trying to improve it...

**Comment by desaintmartin** [comment]
Pfew, tests are passing. So this would require a new review since this contains a new feature.

**Comment by robin-wayve** [comment]
Fixes #12

**Comment by pierluigilenoci** [comment]
Why is everything frozen here? 😢

**Comment by desaintmartin** [comment]
@pierluigilenoci because I think we lack maintainers!

I need a review for this one among the maintainers, maybe @NickMeves ?

**Comment by pierluigilenoci** [comment]
@desaintmartin now there are two more! 🚀 ❤️ 
@NickMeves @tlawrie @NickMeves 

1E04

**Comment by desaintmartin** [comment]
Would you like to help maintaining the chart? ;)

**Comment by pierluigilenoci** [comment]
If you see fit, I can help.

**Review by NickMeves — APPROVED** [review]
LGTM! Sorry for the delay - switched jobs and have been a little MIA lately 😅

**Comment by desaintmartin** [comment]
@pierluigilenoci if you want, open a PR to add yourself as OWNER!

**Comment by pierluigilenoci** [comment]
@desaintmartin https://github.com/oauth2-proxy/manifests/pull/32 done.
Let me know if it is enough.

Side note: the release linked to the changes of this PR is missing.

**Comment by desaintmartin** [comment]
Fixed in https://github.com/oauth2-proxy/manifests/pull/33.

**Pull request merged**
