### PR TITLE
fix Helm repo and update instruction for Helm 3

### PR DESCRIPTION
**Pull request by elnappo**

### CODE REVIEW

**Comment by desaintmartin** [comment]
Thanks! The chart is immutable, even its README: you need to bump the version.

**Comment by elnappo** [comment]
anything missing?

**Comment by desaintmartin** [comment]
No, I haven't been notified of your fixes, sorry!

**Review by desaintmartin — APPROVED** [review]

**Comment by desaintmartin** [comment]
Hey @JoelSpeed, it seems I don't have merge permissions ("write access"), do you mind adding them to me?

**Comment by JoelSpeed** [comment]
@desaintmartin try now?

**Comment by desaintmartin** [comment]
Yes, possible ! thanks!

**Pull request merged**
