### PR TITLE
publish new charts to GHCR OCI registry

### PR DESCRIPTION
**Pull request by jkroepke**
This PR publish helm charts additionally as OCI packages. 

See: https://helm.sh/docs/topics/registries/

### CODE REVIEW

**Comment by jkroepke** [comment]
@desaintmartin can I assist here?

**Comment by jkroepke** [comment]
Please let me know what I can do here to bring this forward.

The code comes from: 

* https://github.com/prometheus-community/helm-charts/blob/main/.github/workflows/release.yaml

and used in multiple repositories.

**Review by pierluigilenoci — APPROVED** [review]

**Comment by jkroepke** [comment]
@pierluigilenoci Thanks! Looking at the CI, the pushs are working fine. By default packages are pushed with access private. Could you please make the artifact in github packages public visible?

**Comment by pierluigilenoci** [comment]
@jkroepke, unfortunately, I can't. 😢
I do not have the permission to change this configuration. 🤷🏻‍♂️

I necessarily have to disturb @JoelSpeed or @NickMeves. Can you solve it? 🙏🏻

**Comment by jkroepke** [comment]
It's still not visible

**Comment by pierluigilenoci** [comment]
@jkroepke still waiting for @JoelSpeed or @NickMeves to do fix that.

**Comment by jkroepke** [comment]
@JoelSpeed or @NickMeves : Can you take a look here?

**Pull request merged**
