### PR TITLE
Correct ServiceAccount name

### PR DESCRIPTION
**Pull request by MXfive**
Use the correct value for the service account name.

### CODE REVIEW

**Comment by pierluigilenoci** [comment]
@MXfive could you please do a Chart version bump?

**Comment by MXfive** [comment]
Done @pierluigilenoci

**Review by pierluigilenoci — APPROVED** [review]

**Comment by pierluigilenoci** [comment]
@desaintmartin could you please take a look also at this?

**Review by desaintmartin — APPROVED** [review]
Thanks!

**Pull request merged**
