### PR TITLE
Add option to set dnsPolicy on pod.

### PR DESCRIPTION
**Pull request by ebuzzz**

### CODE REVIEW

**Review by pierluigilenoci — CHANGES_REQUESTED** [review]
A few things are missing from this PR: 
* Chart version bump
* Default value in `values.yaml` 
* Configuration details inside the README.md 

And maybe something else that I didn't notice

**Comment by pierluigilenoci** [comment]
@ebuzzz is this feature still needed?

**Comment by pierluigilenoci** [comment]
@ebuzzz so?

**Comment by ebuzzz** [comment]
@pierluigilenoci I've changed my intern DNS structure, so this change is no longer needed for my specific use-case.

**Pull request closed without merging**
