### PR TITLE
Support for tpl function in extra env values

### PR DESCRIPTION
**Pull request by abhilashjoseph**
Hello,

Having support to use tpl on the extra env values will be of great help to support environment variables to be able to refer to external secrets resolving names from the release name, chart name or any other variable.

Thanks!!

### CODE REVIEW

**Comment by erkannt** [comment]
This sounds useful, but I can't validate it by looking at it as I'm not familiar with the `tpl` syntax. Could you add a values yaml to the ci folder of the chart that set a regular envvar and one that uses `tpl`? That way we can have CI check it while also documenting.

Might also be worth mentioning in the chart Readme.

**Comment by abhilashjoseph** [comment]
> This sounds useful, but I can't validate it by looking at it as I'm not familiar with the `tpl` syntax. Could you add a values yaml to the ci folder of the chart that set a regular envvar and one that uses `tpl`? That way we can have CI check it while also documenting.
> 
> Might also be worth mentioning in the chart Readme.

@erkannt Thank you for looking into this, I have added the values file with tpl function tests and also have updated readme. Cheers!

**Review by erkannt — APPROVED** [review]
LGTM

**Comment by abhilashjoseph** [comment]
> LGTM

Thank you @erkannt , Please let me know how this makes it into main. I believe I won't be able to do it myself!

**Comment by pierluigilenoci** [comment]
@abhilashjoseph could you please rebase?

**Comment by abhilashjoseph** [comment]
> @abhilashjoseph could you please rebase?

@pierluigilenoci, I have resolved the conflicts, should be able to merge now, thanks!

**Comment by pierluigilenoci** [comment]
@erkannt please take a look.

**Review by erkannt — DISMISSED** [review]

**Comment by abhilashjoseph** [comment]
Resolved conflict again as there were more main commits after my last conflict resolution.

**Review by erkannt — DISMISSED** [review]

**Comment by abhilashjoseph** [comment]
Thank you @erkannt, I'm unable to merge this, can someone help to get this merged?

**Review by pierluigilenoci — DISMISSED** [review]
LGTM

**Comment by pierluigilenoci** [comment]
@desaintmartin I can't approve despite being a maintainer now.
Is it because this branch was forked earlier? 

@abhilashjoseph this PR need a Chart version bump 😉

**Comment by abhilashjoseph** [comment]
> @desaintmartin I can't approve despite being a maintainer now.
> Is it because this branch was forked earlier?
> 
> @abhilashjoseph this PR needs a Chart version bump 😉

The main chart version changed again, I'll bump it up now

**Comment by desaintmartin** [comment]
@pierluigilenoci I think you need to be added as member of this repo (see the related issue).

**Comment by pierluigilenoci** [comment]
@abhilashjoseph IMHO maybe makes sense to rebase from the master.

**Comment by abhilashjoseph** [comment]
> @abhilashjoseph IMHO maybe makes sense to rebase from the master.

@pierluigilenoci  Yes, I just rebased from master and pushed the changes, thank you!

**Review by pierluigilenoci — APPROVED** [review]

**Review by desaintmartin — APPROVED** [review]

**Comment by desaintmartin** [comment]
Let me do this in the meantime.
@abhilashjoseph thanks!

**Pull request merged**
