### PR TITLE
Allow alpha config to come from a template

### LINKED ISSUE #151: Allow templating of alpha config
It would be good to be able to define some parts of the alpha config as a string that is treated as a Helm template, similar to the normal config.

This is of particular use when using oauth2-proxy as a subchart of a parent chart.

### PR DESCRIPTION
**Pull request by mkjpryor**
Fixes #151

### CODE REVIEW

**Comment by pierluigilenoci** [comment]
Thank you so much for your PR.

To approve this PR, the Chart version bump and the modification to the README.md to explain how to use the parameter are missing.
Could you please add them?

**Comment by mkjpryor** [comment]
@pierluigilenoci I realised I didn't add the documentation...! Sorry!

For the version bump, are you expecting a minor or patch version bump? This is obviously a backwards compatible change.

**Comment by mkjpryor** [comment]
@pierluigilenoci 

I added the docs and version bump. I assumed a minor version bump, since this is a feature addition and not just a fix.

**Comment by pierluigilenoci** [comment]
That's fine.
Thanks again.

**Pull request merged**
