### PR TITLE
Feature add host alias

### LINKED ISSUE #57: Add support for setting hostAlias (useful when deploying oauth2-proxy on premise)
I would like to suggest a PR for https://github.com/k8s-at-home/charts/issues/932, so I'm opening the same issue here.

Original issue:
On premise installation we would like to set hostAlias to the pod. Using oauth2-proxy-5.0.5 we can add the config to pod:
120691727-d1339080-c474-11eb-85be-31cea62bb6d1

I would like to be able to set hostAlias from the values.yaml

### PR DESCRIPTION
**Pull request by lgthibault**
Fixes #57 (itself a copy of https://github.com/k8s-at-home/charts/issues/932)
Allows to inject an additional entry in /etc/hosts. 

Cannot shake the feeling this is a dirty trick, but maybe this can be useful to others as well.

### CODE REVIEW

**Comment by lgthibault** [comment]
Tested using helm install, and both ct commands listed in README.md as well.

**Comment by pierluigilenoci** [comment]
@lgthibault could you please rebase and fix the conflict?

**Comment by lgthibault** [comment]
I merged instead of rebasing, let me know if this creates problems.

**Comment by pierluigilenoci** [comment]
Could you please remove the Redis tgz?

**Comment by lgthibault** [comment]
Removed redis tgz and bumped Chart.yaml version.

**Comment by pierluigilenoci** [comment]
Unluckily @lgthibault the PR needs another bump to the chart version.

**Comment by lgthibault** [comment]
Chart version bumped to 5.0.7.

**Comment by pierluigilenoci** [comment]
@desaintmartin could you please take a look?

**Review by desaintmartin — CHANGES_REQUESTED** [review]
Sorry for the huuuge delay.
Could you rebase (it should be easy) and bump a minor version of the chart (according to semver, this is new feature) instead of patch version?

**Comment by pierluigilenoci** [comment]
@desaintmartin could you please take a look?

**Review by desaintmartin — APPROVED** [review]

**Pull request merged**
