### PR TITLE
Add a custom templates example in the documentation

### PR DESCRIPTION
**Pull request by fungiboletus**
Related to https://github.com/oauth2-proxy/oauth2-proxy/issues/1507

### CODE REVIEW

**Comment by pierluigilenoci** [comment]
@JoelSpeed could you please take a look?

**Comment by desaintmartin** [comment]
Could you bump Chart.yaml version?

**Comment by pierluigilenoci** [comment]
@desaintmartin this is a documentation change only. Does it really need to rebase?

**Comment by desaintmartin** [comment]
In theory, the whole chart, including readme or comments in values, is immutable, and chart-releaser will complain trying to release an existing version. This makes sense when you see https://artifacthub.io/packages/helm/oauth2-proxy/oauth2-proxy that fetches the readme.

**Comment by pierluigilenoci** [comment]
@fungiboletus could you please do a version bump on the chart?

**Comment by pierluigilenoci** [comment]
@desaintmartin to speed up I fixed the PR. Could you please take a look?

**Review by pierluigilenoci — APPROVED** [review]

**Review by desaintmartin — APPROVED** [review]

**Comment by fungiboletus** [comment]
> @fungiboletus could you please do a version bump on the chart?

Sorry I missed the notifications. Thanks for merging the pull request!

**Pull request merged**
