### PR TITLE
don't override ct.yml in the release workflow

### PR DESCRIPTION
**Pull request by erkannt**
We have a `ct.yml` that configures the chart-releaser-action. So no need to have the values here.

### CODE REVIEW

**Review by JoelSpeed — APPROVED** [review]

**Comment by JoelSpeed** [comment]
Fingers crossed!

**Comment by SeWieland** [comment]
Hm.. That didn't work I guess..
I can only imaging that the action script checks if there are any changed files under the defined path since the last commit.
That was not the case here, so maybe it'll need an initial change to one of the chart files in order to produce a release?

**Comment by billimek** [comment]
@SeWieland yes I'm nearly positive that a minor bump to the chart version in `Chart.yaml` and subsequent merge to the main branch will trigger a successful publish.

**Comment by JoelSpeed** [comment]
The problem is with the chart releaser script, it cannot handle the charts dir being prefixed with `./`, see https://github.com/oauth2-proxy/manifests/issues/6#issuecomment-774500210

**Pull request merged**
