### PR TITLE
add autoscaling

### PR DESCRIPTION
**Pull request by sja**

### CODE REVIEW

**Comment by pierluigilenoci** [comment]
@sja, please add a helm chart bump and edit the artifacthub.io/changes section.

**Comment by sja** [comment]
Thanks @pierluigilenoci  for that info. I did a minor version bump, as it adds a feature. It is backwards compatible, old values do not change the result.

**Comment by sja** [comment]
@pierluigilenoci I updated the MR again, inspired from the other MRs. Feel free to reach out to me, especially if you want me to modify the version numbers to not have a conflict. Usually, I react in 1 business day.

**Comment by sja** [comment]
I added that, but I'm not familar with how to validate the result. Are the results compared to an expected value somewhere or is that more like a smoke test if the values can be rendered at all?

**Review by pierluigilenoci — APPROVED** [review]

**Comment by pierluigilenoci** [comment]
@sja Usually, the test results are visible in the [pipeline](https://github.com/oauth2-proxy/manifests/actions/runs/9301491337/job/25609773690). 
In this case, they are not, and I don't understand why.
However, from the point of view of the feature, this PR is OK like this.

**Comment by pierluigilenoci** [comment]
@sja ok, fixed https://github.com/oauth2-proxy/manifests/pull/211 🚀

**Comment by pierluigilenoci** [comment]
@sja Thank you.

**Pull request merged**
