### PR TITLE
Added myself as a maintainer

### PR DESCRIPTION
**Pull request by pierluigilenoci**
Ref: https://github.com/oauth2-proxy/manifests/pull/29#issuecomment-850183123

### CODE REVIEW

**Review by desaintmartin — APPROVED** [review]

**Comment by desaintmartin** [comment]
I'd like another maintainer to approve as well!
@oauth2-proxy/manifest-maintainers

**Comment by pierluigilenoci** [comment]
@desaintmartin I'm sorry but I'm afraid I missed something. What should I do?

**Comment by desaintmartin** [comment]
I just wanted confirmation from another maintainer!

**Review by morganchristiansson — APPROVED** [review]

**Comment by morganchristiansson** [comment]
I'm not a maintainer but I approve :+1:

**Review by JoelSpeed — APPROVED** [review]
LGTM! Welcome to the team @pierluigilenoci

**Comment by desaintmartin** [comment]
Welcome!

**Comment by desaintmartin** [comment]
@JoelSpeed could you add @pierluigilenoci as maintainer member for the org?

**Comment by JoelSpeed** [comment]
Invitation sent

**Comment by pierluigilenoci** [comment]
Thank you!

**Pull request merged**
