### PR TITLE
Feature/use redis secret

### PR DESCRIPTION
**Pull request by bluebrown**
Use redis subchart secret if existing secret and password are not set

Signed-off-by: Nico Braun <rainbowstack@gmail.com>

fixes: #84

### CODE REVIEW

**Comment by bluebrown** [comment]
Builds on top an enhances #83   by abstracting the redis fullname

**Comment by pierluigilenoci** [comment]
@bluebrown I would wait for #83 to be merged before even starting to watch this PR. 😜

**Comment by bluebrown** [comment]
@pierluigilenoci , yes makes sense. I will apply the suggested changes of #83 and use them in this PR to get the secret name to use. Because the secret name is essentially the redis.fullname helper.

**Comment by pierluigilenoci** [comment]
@bluebrown now you can rebase and move forward also this PR. 🚀

**Comment by bluebrown** [comment]
This is getting quite messy. I will create a fresh branch from main and copy my changes over.

**Pull request closed without merging**
