### PR TITLE
Uses template function to generate service account name

### PR DESCRIPTION
**Pull request by caiofralmeida**
I would like to override the service account name instead use the default full name.

Signed-off-by: Caio Almeida <caio.almeida@gympass.com>

### CODE REVIEW

**Comment by pierluigilenoci** [comment]
@caiofralmeida you need to add the chart version bump.

Note: This is a very strange bug. It seems incredible to me that no one has noticed before.

**Comment by caiofralmeida** [comment]
@pierluigilenoci fixed, thanks!

**Comment by pierluigilenoci** [comment]
@desaintmartin sorry to bother you but the chart test fail miserably 😞

**Comment by desaintmartin** [comment]
Looks like infrastructure-related test failure (the kube node from kind was not ready), retrying...

**Comment by desaintmartin** [comment]
Weird. I've just successfully tested a change here: https://github.com/oauth2-proxy/manifests/pull/42
I've upgraded CI tools to their latest version, could you rebase? I doubt it comes from this but it does not harm.

**Comment by pierluigilenoci** [comment]
@caiofralmeida could you please rebase?

**Comment by caiofralmeida** [comment]
> @caiofralmeida could you please rebase? And maybe squash all the commits? And fix the chart bump?

@pierluigilenoci, done.
Could you check, please if it's ok? thanks.

**Review by pierluigilenoci — APPROVED** [review]

**Pull request merged**
