### PR TITLE
[WIP] Update Redis subchart update to the latest version

### LINKED ISSUE #26: Upgrade redis subchart to the latest version
Now the chart uses a really old Redis chart. Could be nice to upgrade it to the latest version. Thanks.

### PR DESCRIPTION
**Pull request by pierluigilenoci**
Fixes #26

### CODE REVIEW

**Comment by desaintmartin** [comment]
Maybe this is a breaking change, a lot of values changed between v10 and v14.

**Comment by pierluigilenoci** [comment]
@desaintmartin this PR is still a WIP. I tried to figure out what the changes in the chart from version 10 to 14 have been but the Bitnami repo is an hell. There are no releases and it is not easy to track the versions of the charts. 😞 

Any suggestions?

**Comment by desaintmartin** [comment]
Bitnami guys kept using this good practice we set up on chart.git: having a migration guide in the README! It is quite helpful, i've done exactly the same a few weeks ago on a proprietary chart.

**Comment by GabrielMajeri** [comment]
@pierluigilenoci what can we do to help move this PR forward?

**Comment by pierluigilenoci** [comment]
@GabrielMajeri I just have to find the time to finish it. I do not know if I can in the coming days.

If this is something you need urgently feel free to open a PR with the necessary changes.

**Comment by pierluigilenoci** [comment]
Another PR like this: https://github.com/oauth2-proxy/manifests/pull/79

**Comment by pierluigilenoci** [comment]
Fixed with #79

**Pull request closed without merging**
