### PR TITLE
Correct outdated links to old repositories

### PR DESCRIPTION
**Pull request by robin-wayve**
Please check that I got each of these right 🙇🏻 

- `pusher/oauth2_proxy` -> `oauth2-proxy/oauth2-proxy`
- `helm/charts/stable/oauth2-proxy` -> `oauth2-proxy/manifests/helm/oauth2-proxy`
- `pusher.github.io` -> `oauth2-proxy.github.io/docs`

### CODE REVIEW

**Comment by robin-wayve** [comment]
I see now that I'm going over some of the same ground as #29 🙈

**Comment by robin-wayve** [comment]
@desaintmartin do you think it's worth merging this ahead of #29 ?

**Comment by desaintmartin** [comment]
Let's do it, I'll rebase once I have a review on my PR.

Could you bump patch version? All charts are immutable, including doc.

**Comment by desaintmartin** [comment]
Oops, this probably needs a rebase.

**Review by desaintmartin — APPROVED** [review]

**Comment by desaintmartin** [comment]
Thanks!

**Pull request merged**
