### PR TITLE
Allow configuring terminationGracePeriodSeconds and lifecycle hooks

### PR DESCRIPTION
**Pull request by karel1980**
Please accept my humble PR.
These changes would help with zero downtime deployments on EKS.

For sources, please see these issues:
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2366
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1064

### CODE REVIEW

**Comment by pierluigilenoci** [comment]
@karel1980 Thank you for your contribution. 

The PR needs a [bump of the Chart version](https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/Chart.yaml#L2) and an [annotation for aAtifactHub](https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/Chart.yaml#L35-L41) to be approved.

**Comment by karel1980** [comment]
Will do. Thanks for the quick feedback.

**Comment by karel1980** [comment]
@pierluigilenoci I've made the requested changes. I'm not familiar with artifacthub.io, I'm guessing the fix from the 6.19.1 release needed to be removed. If not, let me know I'll add it back in a jiffy

**Review by pierluigilenoci — APPROVED** [review]

**Review by pierluigilenoci — APPROVED** [review]

**Comment by pierluigilenoci** [comment]
@karel1980 Thank you for your contribution!

**Pull request merged**
